server:
  port: 8083

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: logging-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/consort_group
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: consort-redis-logging-service
      port: 6379

kafka:
  bootstrap-servers: kafka:9092
  consumer-group-id: logging-group
  session-timeout-ms: 10000
  max-partition-fetch-bytes: 1048576
  max-poll-records: 500
  max-poll-interval-ms: 300000
  super-admin-action: super-admin-action-topic
  mentor-action: mentor-action-topic
  hr-action: hr-action-topic
